### ISSUE TITLE
Resolving Block Definitions with Different Name from Bower Component

### ISSUE THREAD

**Issue by datkins10** [WebBlocks/WebBlocks#65]
Right now, getting crashes like:

```
/Users/Master/.rvm/gems/ruby-2.2.1/gems/web_blocks-2.0.5.alpha/lib/web_blocks/structure/framework.rb:24:in `instance_eval': No such file or directory @ dir_initialize - /Users/Master/Sites/enterprise/resources/blocks/widgets (Errno::ENOENT)
```

The def for this, inside of a bower_component, is:

```ruby
block 'cloudcompli' do
  block 'common', path: blocks_path do
    register_facade :recursive_file_names_block, ::WebBlocks::Facade::RecursiveFileNamesBlock
    recursive_file_names_block 'widgets'
  end
end
```

**Comment by ebollens** [comment]
It turns out this has nothing to do with `recursive_file_names_block`. Instead, the actual bug is with the way that the pathing is resolved when a block is loaded as a component into the framework.

Specifically, consider this:

```ruby
      def register hash
        name = hash[:name]
        path = hash[:path]
        resolved_block_path = resolved_path + path
        blockfile_path =  resolved_block_path + "Blockfile.rb"
        raise "Undefined blockfile for #{path}" unless File.exists?(blockfile_path)
        isolated_facade_registration_scope do
          block name do
            set :base_path, resolved_block_path
          end
          instance_eval File.read(blockfile_path)
        end
      end
```

The problem is that the component name for @datkins10's example is `cloudcompli-common`, but the block that it's defining is `common` under `cloudcompli`.

**Comment by ebollens** [comment]
878f390 resolves the exact issue described here, but it doesn't account for cases where multiple blocks might be defined in this file. I'm thinking what I want to do is isolate sub-graphs, if they use `scoped_base_path`, allowing multiple blocks to share the same `scoped_base_path`. Will explain with a full example once I make the additional tweak.

**Comment by ebollens** [comment]
My last commit made it possible to do something like this:

```ruby
require 'web_blocks/facade/recursive_file_names_block'

register_facade :recursive_file_names_block, ::WebBlocks::Facade::RecursiveFileNamesBlock

block 'test' do

  recursive_file_names_block 'efx', path: 'src' do |efx|

    block 'engine', required: true do
      loose_dependency framework.route 'jquery'
    end

    block 'driver' do
      dependency efx.route 'engine'
    end

  end

end
```

However, where it would fall apart is this:

```ruby
require 'web_blocks/facade/recursive_file_names_block'

register_facade :recursive_file_names_block, ::WebBlocks::Facade::RecursiveFileNamesBlock

block 'test' do

  block 'abc', path: 'abc' do

  end

  recursive_file_names_block 'efx', path: 'src' do |efx|

    block 'engine', required: true do
      loose_dependency framework.route 'jquery'
    end

    block 'driver' do
      dependency efx.route 'engine'
    end

  end

end
```

This would happen because of this:

```ruby
      extend_method :set_parent do |parent|
        parent_method parent
        if has_scoped_base_path?
          if has? :path
            set :path, "#{scoped_base_path}/#{get :path}"
            forget_scoped_base_path!
          end
        end
      end
```

Basically, as soon as it accessed the scoped path, it would forget it.

What we want instead is to partition a subgraph, once it sees the scoped path, so that it will not resolve this scoped path from outside the subgraph, but, if another branch outside of the subgraph hasn't already used the scoped path, then it should be able to as well.

The solution is to update `set_parent` as:

```ruby
      def isolate_subgraph_from_scoped_base_path!
        @isolated_from_parent_scoped_base_path = true
      end

      extend_method :set_parent do |parent|
        parent_method parent
        if has_scoped_base_path?
          if has? :path
            set :path, "#{scoped_base_path}/#{get :path}"
            isolate_subgraph_from_scoped_base_path!
          end
        end
      end
```

And then test against `@isolated_from_parent_scoped_base_path` in `has_scoped_base_path?` and `scoped_base_path`, and remove the instance variable on `forget_scoped_base_path!`, which should still occur `with_base_path`.

**Comment by ebollens** [comment]
This was a **high risk** change. Unit tests pass, but that's not to say it didn't break anything. Testing will definitely be needed.
